bbsnote/urls.py
#config 아래에만 url을 주구창창 넣으면 너무 복잡해지니! bbsnote관련 url은 쪼개서 여기서 작업하자.

from django.urls import path
from . import views

app_name = 'bbsnote'

urlpatterns = [
    path('',views.index, name='index'), #config/urls -> bbsnote/urls -> bbsnote/views.py 실행!
    path('<int:board_id>/',views.detail, name='detail'),
    # url을 정의해주고, views 아래 detail함수를 불러온다 -> 
    # int는 path_converter라 부르는 기능. board_id는 컨버터를 통해 반환 받은 값(int는 board_id에 숫자가 매핑되었음을 의미)
    # <type: name>으로 작성됨. 지정한 타입의 name변수를 view함수로 넘기는 역할이다.
    # converter를 쓰는 이유는, board_id가 게시글별로 바뀌기 때문이다.
    # 이런 path_converter는 str, int, slug(영문대소문자,숫자,-,_), uuid(모든 문자 소문자, - 포함), path(str + /) 가 있다.
    path('comment/create/<int:board_id>/', views.comment_create, name='comment_create'),
    # 해당 게시글의 댓글임을 표시하기 위해 commnet url에도 board_id를 넣어줌!
    path('board/create/', views.board_create, name='board_create'),
]

common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from bbsnote import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bbsnote/', include('bbsnote.urls')), #bbstnote라는 주소로 들어오게 되면, bbsnote아래 urls.py로 보내겠다.
    path('common/', include('common.urls')), # common으로 들어올 경우!(로그인,로그아웃 기능 사용할경우) common.urls.py로 보내도록
    path('',views.index, name='index'), #지금까지는 url에 아무것도 입력하지 않으면 404가 출력되었음. 그걸 방지하기 위함
]

bbsnote/models.py
from django.db import models

# 게시판 모델 만들기 : 아래와 같이 두개의 클래스를 만들었다는 것은, 2개의 테이블을 만든 것과 같음. 이대로 DB에 올릴것!
# Create your models here.
class Board(models.Model): #게시글 모델, Model은 DB에서 가져오는것 => DB에 테이블을 가져올 것!
    subject = models.CharField(max_length=200) #게시글 제목임! 최대 문자열 길이를 200으로.
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self): 
        #이 객체(Board=self)를 호출했을 때 리턴하고자 하는 값을 세팅해주는 함수. : 여기선 제목 호출해주는!!
        return self.subject

class Comment(models.Model): #댓글 모델, Model은 DB에서 가져오는것
    board = models.ForeignKey(Board, on_delete=models.CASCADE)#해당하는 게시글의 댓글이란 의미로 Foreign키 속성 부여
    #on_delete, CACADE면! => 같이 지워지라는 것. 게시글이 사라지면 댓글도 사라지도록!!
    #이렇게 Foreign키 지정이 가능한 이유는 migrate하면서 장고에서 자동으로 migrations 아래에 Board와 Comment에 대한 id를 만들고, PK 지정을 해주기 때문.
    content = models.TextField()
    create_date = models.DateTimeField()

common/models.py
from django.db import models

# Create your models here.

bbsnote/forms.py
#forms.py를 통해 게시글 등록 기능 만들기.
from django import forms
from bbsnote.models import Board
# BoardForm은 프론트와 백엔드(모델:Board) 간의 중간다리 역할을 해줌!
class BoardForm(forms.ModelForm):
    class Meta:
        model = Board #참조하고자 하는 모델이 Board고!
        fields = ['subject', 'content'] #프론트에 있는 Form에서subject와 content를 넘겨받아 백엔드의 BOARD(모델)로 넘겨주겠다!

common/forms.py
#회원가입 기능 추가하지
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta: #메타는 꼭 있어야 한다.
        model = User
        fields = ("username", "email")

bbsnote/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Board, Comment
from django.utils import timezone
from .forms import BoardForm
from django.core.paginator import Paginator #게시판 페이징 적용하기

# Create your views here.
def index(request): #index 함수 정의 : 매개변수는 request(요청)/ 요청이 들어오게 되면 index를 실행시켜라!
    #입력 인자
    page = request.GET.get('page', 1)
    #조회
    board_list = Board.objects.order_by('-create_date') #-create_date를 기준으로 Board 내 데이터 정리.
    #페이징 처리 : 전체 데이터를 기준으로 해서 페이징을 잡아야 한다.
    paginator = Paginator(board_list, 5) #board_list를 1페이지에 5개씩 끊어서 보겠다
    page_obj = paginator.get_page(page) #page_obj 변수에 paginator의 페이지 정보를 가져와 넣겠다.
    #context에 board_list를 그대로 넣는 게 아닌 page_obj를 넣겠다.->여기까지 하면 1페이지(5개)만 보이고 짤린다!
    #이제 프론트 단에서 이후 페이지도 출력되도록 해줘야 한다!(board_list.html에 작성)
    context = {'board_list': page_obj} # context(키는 보드리스트, 값은 위에 정의한 board_list)를 딕셔너리로 정의. 
    #return HttpResponse("bbsnote에 오신 것을 환영합니다!");
    return render(request, 'bbsnote/board_list.html', context) 
    #render 함수! request 정보 기준으로 board_list.html 템플릿에 context 딕셔너리 데이터를 바인딩 시켜서 넘겨주겠다!
    #그러면 bbsnote/ url로 리퀘스트 왔을 때 => views아래 index 함수를 실행하게 되고 => models 아래 Board 모델을 불러옴.
    #=> Board 문서를 불러온 뒤 -create_date(앞에 - 가 붙어서 desc로 create_date 기준하여 불러옴)를 기준으로 불러왔고
    #=> render 함수를 통해 이 정보를 board_list.html로 context 정보를 바인딩해준 뒤, board_list 안 내용대로 완성해
    #=> 클라이언트한테 다시 보내준 것이다.



#상세 페이지 기능 구현하기
def detail(request, board_id):
    board = Board.objects.get(id=board_id) #요청 정보를 가지고옴. SELECT * FROM bbsnote_Board WHERE id=3 과 같다.(3은 유동적)
    context = {'board':board}
    return render(request,'bbsnote/board_detail.html',context) #detail함수에 context에 담긴 정보를 담아 바인딩한다!

def comment_create(request, board_id):
    board =Board.objects.get(id=board_id)
    # comment = Comment(board=board, content=request.POST.get('content'), create_data=timezone.now())
    # comment.save()
    board.comment_set.create(content=request.POST.get('content'), create_date=timezone.now())
    #위 표현이나 위 두줄 표현이나 같다!
    return redirect('bbsnote:detail', board_id=board.id)
#redirect 는 render하고 다르게 데이터를 바인딩 해 보내는 것이 아니라, 현재 받은 함수 안의 board 정보의 id 값을 그대로 받아서 넘김.
#그리고 models 에 Comment 클래스를 넣어놓긴 했지만, 기능만 구현해 둔 것으로 아직 댓글남기는 기능은 추가해두지 않았다!

def board_create(request):
    if request.method == 'POST':
        form = BoardForm(request.POST) #form을 POST방식으로 들어온 리퀘스트 전부다 BoardForm으로!
        if form.is_valid(): #위 조건에 만족한다면
            board = form.save(commit=False) #데이터를 저장은 하겠지만, 커밋은 아직 안하겠다!
            board.create_date = timezone.now() #제목과 내용이 등록될 때, 작성시점도 저장되도록!(이때문에 위에 커밋을 안한것)
            board.save() #세이브하고 커밋해줘. save의 기본값이 commit=True임!
            return redirect('bbsnote:index')
    #위 큰 if문은 데이터가 있으면 그대로 보내고.. else의 경우! 입력할 수 있는 창을 띄우도록 하는 것!
    else:
        form = BoardForm()
    return render(request, 'bbsnote/board_form.html', {'form':form})
    # 즉 board_create함수에 form(프론트에서 데이터 작성..)에 작성된 데이터를 바인딩한다(subject, content, timezone)

common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login

from .forms import UserForm

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST) #UserForm에서 요청 들어온거 다 받은다음에
        if form.is_valid(): #요청 들어온게 POST인거 모두
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1') 
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form':form})

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <title>게시판 노트</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
{% comment %} <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start --> {% endcomment %}
{% comment %} {% block script %}
{% endblock %} {% endcomment %}
<!-- 자바스크립트 End -->
</body>
</html> 

templates/bbsnote/board_detail.html
<h1>{{board.subject}}</h1>
<div>
    {{board.content}}
</div>

<h5>{{board.comment_set.count}}개의 댓글이 있습니다.</h5>
<div>
    <ul>
        {% for comment in board.comment_set.all %}
            <li>{{comment.content}}</li>
        {% endfor %}
    </ul>
</div>
{% comment %} form 태그는 정보를 담아 백엔드에 보내주는 애! csrf 공격을 막기 위함. {% endcomment %}
<form action= "{% url 'bbsnote:comment_create' board.id %}" method= "POST" >
    {% comment %} 지금현재 작성되는 게시글에게 이 커멘트를 등록시켜주겠어, 라는 실행문이다. {% endcomment %}
    {% csrf_token %}
    <textarea name= "content" id= "content" rows= "15" ></textarea>
    <input type= "submit" value= " 댓글달기 " >
    {% comment %} 백엔드로 보내주기 위한 submit(댓글달기):댓글달기를 누르는 순간 views.comment_create 에 redirect가 실행되는것. 버튼 추가 {% endcomment %}
    </form>

templates/bbsnote/board_form.html
{% extends 'base.html'  %}
{% block content  %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">게시글 등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">저장</button>
    </form>
</div>
{% endblock  %}

templates/bbsnote/board_list.html
{% extends 'base.html' %}
{% load bbsnote_filter %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center thead-dark"> 
            <th></th>           
            <th style="width:50%">제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if board_list %}
        {% for board in board_list %}
        <tr class="text-center">
            <td>{{ board_list.paginator.count|sub:board_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <td class="text-left">
                <a href="{% url 'bbsnote:detail' board.id %}">{{ board.subject }}</a>                
            </td>            
            <td>{{ board.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table> 
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if board_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ board_list.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in board_list.paginator.page_range %}
        {% if page_number >= board_list.number|add:-5 and page_number <= board_list.number|add:5 %}
            {% if page_number == board_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if board_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ board_list.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href="{% url 'bbsnote:board_create' %}" class="btn btn-primary">등록</a>   
</div>
<form id="searchForm" method="get" action="{% url 'index' %}">    
    <input type="hidden" id="page" name="page" value="{{ page }}">    
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });     
});
</script>
{% endblock %}

templates/bbsnote/board_list_studying.html
{% comment %} 템플릿 태그로 작성하면 장고에서 해당 html에 데이터가 바인딩 되었음을 확인하고 실행해주는 것! {% endcomment %} 
{% comment %} {{board_list}} 어떻게 출력되는지 확인해보자.이게바로 views밑에 context 데이타다.  {% endcomment %}
{% extends 'base.html' %}
{% comment %} base.html을 상속받아 애를 기준으로 기준을 잡을거야!-> block, endblock 사이에 내용 구상! {% endcomment %}
{% block content %}
{% if board_list %} {% comment %} 템플릿 태그 {% endcomment %} 
    <ul>
        {% for board in board_list %} {% comment %} board_list 안 데이터 전부 순회하라 {% endcomment %} 
        <li><a href= "{% url 'bbsnote:detail' board.id %}" >{{board.subject}}</a></li> 
        {% comment %}a태그를 통해 상대경로를 넣어줬음. 절대경로란(처음부터 끝까지 다 링크로 넣는 것) {% endcomment %} 
        {% comment %}board id가 url에 출력되고, 템플릿에는 board 제목(subject)가 표시되도록 ul-li대로. {% endcomment %} 
        {% endfor %}
    </ul>
{% else %}
    <p>글이 없습니다.</p> {% comment %}만약 board_list안에 데이터가 없다면! 해당 메시지 출력{% endcomment %} 
{% endif %}
{% endblock %}

templates/common/login.html
{% extends "base.html" %}
{% block content  %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html"  %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{form.username.value|default_if_none:''}}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{form.password.value|default_if_none:''}}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock  %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:''  }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:''  }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'bbsnote:index' %}">BBSNote</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated  %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login'  %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>